### PR TITLE
Accessibility fixes

### LINKED ISSUE #87: The link to the Ohio State home page in the banner displays “OSU.EDU” but a screen reader announces it as “The Ohio State University”
The link to the Ohio State home page in the banner displays “OSU.EDU” but a screen reader announces it as “The Ohio State University”. Logos especially should announce exactly as how they are read if made of text. 
 
•	[WCAG 2.5.3 Label in Name](https://www.w3.org/WAI/WCAG21/quickref/#label-in-name)
•	Recommendation: Since it is a background image, remove the link text as it both inaccurate and redundant. Change the title attribute to read, “OSU.EDU, home”. 
•	Priority: Moderate

### LINKED ISSUE #88: Secondary badges do not meet color contrast requirements
•	Element has insufficient color contrast of 3.03 (foreground color: #ffffff, background color: #1aaa55, font size: 9.0pt (12px), font weight: normal). Expected contrast ratio of 4.5:1
•	[WCAG 1.4.](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum)3 Contrast (Minimum)
•	Recommendation: Darken the text to meet the requirement.

### LINKED ISSUE #89: Anytime the blue text link color `#2f7aba` is used against any background color other than white, it does not meet contrast requirements.
Anytime the blue text link color #2f7aba is used against any background color other than white, it does not meet contrast requirements.  
•	Table rows: Element has insufficient color contrast of 4.32 (foreground color: #2f7aba, background color: #f9f9f9, font size: 12.0pt (16px), font weight: normal). Expected contrast ratio of 4.5:1
•	warning alert: Element has insufficient color contrast of 4.25 (foreground color: #2f7aba, background color: #f6f6f4, font size: 12.0pt (16px), font weight: normal). Expected contrast ratio of 4.5:1
•	[WCAG 1.4.3 Contrast (Minimum)](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum)

### LINKED ISSUE #90: Brand Footer: Do not include the title attribute unless having additional information appear upon hover is essential.
The OSU logo image in the footer contains both alt text and a title. Screen readers announce both, leading to redundancy in the announcement.  
•	This is a WCAG Best Practice
•	Recommendation: Remove titles from images unless it provides essential additional information that cannot be delivered any other way.

### LINKED ISSUE #92: DataTable: The same visible arrows, when in a non-sorted state and using the gray `#cccccc`, do not meet the 3:1 color contrast ration requirement for non-text components.
•	[WCAG 1.4.11 Non-Text Contrast](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast)
•	Recommendation: Darken the gray until 3:1 is reached.

For context (from PI Portal wcag eval):
image

### PR DESCRIPTION
**Pull request by helloLilyX**
Fixed #94. Added an `aria-expanded` attribute to the button element in `Filters.Group`

Fixed #91. Added a `<span className='sr-only'>send an email to </span>` in `EmailLink`

Fixed #90. Removed `title="The Ohio State University home page"` from the OSU logo image in the footer

Fixed #87. Changed the text of the link to the Ohio State home page to "OSU.EDU, Home"

Fixed #89. Updated `$link-color` in `_settings.scss`

Fixed #88. Updated `.filters {&-pill {&:hover {color: #333333;}` in `_filters.scss`

Fixed #92. Updated the color for `p-column-title` to meet the 4.5:1 contrast ratio requirement and `p-sortable-column-icon` to meet the 3:1 contrast ratio requirement

Fixed issue 35 in PI Portal Accessibility Evaluation Report. Added `DataTable` and `border` for the focused sortable header cells in `DataTable`

### CODE REVIEW

File: src/core-application/OhioStateNavbar/index.tsx [hunk 1]
```diff
@@ -1,25 +1,54 @@
...
-                <li><a href="https://www.osu.edu/map/" className="osu-navbar-map">Map</a></li>
-                <li><a href="https://www.osu.edu/findpeople.php" className="osu-navbar-findpeople">Find People</a></li>
-                <li><a href="https://email.osu.edu/" className="osu-navbar-webmail">Webmail</a></li>
-                <li><a href="https://www.osu.edu/search/" className="osu-navbar-search">Search Ohio State</a></li>
-            </ul>
-        </div>
-    </nav>
+  <nav className="osu-navbar" aria-label="Ohio State nav bar">
+    <div className="osu-navbar-info">
+      <a href="https://osu.edu" title="OSU.EDU, home" />
```
Comment (McManning) [inline src/core-application/OhioStateNavbar/index.tsx:9]:
```suggestion
      <a href="https://osu.edu">OSU.EDU, home</a>
```

Everything else looks good, only correction would be to swap this link content out of the title.

**Review by McManning — CHANGES_REQUESTED** [review]

**Comment by McManning** [comment]
Issue #90 and #87 are covered by this PR.

**Comment by helloLilyX** [comment]
Fixed #89
